Web/GyandhaaraLibrary.View/Controllers/BookController.cs
using GyandhaaraLibrary.DataModel;
using GyandhaaraLibrary.Service;
using GyandhaaraLibrary.Service.Interfaces;
using GyandhaaraLibrary.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GyandhaaraLibrary.View.Controllers
{
    public class BookController : Controller
    {
        IBookService bookService;
        ILanguageService languageService;
        IGenreService genreService;

        public BookController()
        {
            bookService = new BookService();
            languageService = new LanguageService();
            genreService = new GenreService();
        }

        public ActionResult Index()
        {
            var sourceList = bookService.GetAll();

            List<BookListViewModel> targetList = new List<BookListViewModel>();
            foreach (var source in sourceList)
            {
                var languageName = languageService.FindBy(x => x.LanguageID == source.LanguageID).Name;
                var genreName = genreService.FindBy(x => x.GenreID == source.GenreID).Name;
                BookListViewModel target = new BookListViewModel
                {
                    BookID = source.BookID,
                    Edition = source.Edition,
                    Title = source.Title,
                    Author = source.Author,
                    PublishDate = source.PublishDate.ToShortDateString(),
                    Publisher = source.Publisher,
                    Genre = genreName,
                    Language = languageName

                };
                targetList.Add(target);
            }

            return View(targetList);
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            CreateBookVM viewmodel = new CreateBookVM();
            viewmodel.Genres.Add(new GenreDropDownVM { GenreID = 1, Name = ".NET" });
            viewmodel.Languages.Add(new LanguageDropDownVM { LanguageID = 1, Name = "English" });
            viewmodel.Suppliers.Add(new SupplierDropDownVM { SupplierID = 1, Name = "Gyandhaara Book Store" });
            return View(viewmodel);
        }

        [HttpPost]
        public ActionResult Create(CreateBookVM source, int? GenreID, int? LanguageID, int? SupplierID, HttpPostedFileBase file)
        {
            try
            {
                Book target = new Book
                {
                    Code = source.Code,
                    Title = source.Title,
                    Isbn = source.Isbn,
                    Edition = source.Edition,
                    EntryDate = source.EntryDate.Value,
                    Publisher = source.Publisher,
                    PublishDate = source.PublishDate.Value,
                    TotalPages = source.TotalPages.Value,
                    Author = source.Author,
                    Price = source.Price.Value,
                };
                if (file.ContentLength > 0)
                {
                    target.Photo.Image = new byte[file.ContentLength];
                    file.InputStream.Read(target.Photo.Image, 0, file.ContentLength);
                    target.Photo.FileName = file.FileName;
                }
                bookService.Add(target);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            var source = bookService.FindBy(x => x.BookID == id);
            CreateBookVM target = new CreateBookVM
            {
                Code = source.Code,
                Title = source.Title,
                Isbn = source.Isbn,
                Edition = source.Edition,
                EntryDate = source.EntryDate,
                Publisher = source.Publisher,
                PublishDate = source.PublishDate,
                TotalPages = source.TotalPages,
                Author = source.Author,
                Price = source.Price,
                GenreID = source.GenreID,
                SupplierID = source.SupplierID,
                PhotoID = source.PhotoID,
                LanguageID = source.LanguageID
            };

            target.Photo.Image = source.Photo.Image;
            return View(target);
        }

        [HttpPost]
        public ActionResult Edit(int id, CreateBookVM source, int? GenreID, int? LanguageID, int? SupplierID, HttpPostedFileBase file)
        {
            try
            {
                Book target = new Book
                {
                    Code = source.Code,
                    Title = source.Title,
                    Isbn = source.Isbn,
                    Edition = source.Edition,
                    EntryDate = source.EntryDate.Value,
                    Publisher = source.Publisher,
                    PublishDate = source.PublishDate.Value,
                    TotalPages = source.TotalPages.Value,
                    Author = source.Author,
                    Price = source.Price.Value,
                };
                if (file.ContentLength > 0)
                {
                    target.Photo.Image = new byte[file.ContentLength];
                    file.InputStream.Read(target.Photo.Image, 0, file.ContentLength);
                    target.Photo.FileName = file.FileName;
                }
                bookService.Edit(target);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Web/GyandhaaraLibrary.View/Controllers/GenreController.cs
using GyandhaaraLibrary.DataModel;
using GyandhaaraLibrary.Service;
using GyandhaaraLibrary.Service.Interfaces;
using GyandhaaraLibrary.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GyandhaaraLibrary.View.Controllers
{
    public class GenreController : Controller
    {
        IGenreService genreService;
        public GenreController()
        {
            genreService = new GenreService();
        }


        public ActionResult Index()
        {
            List<GenreVM> targetList = new List<GenreVM>();
            IEnumerable<Genre> sourceList = genreService.GetAll().ToList();
            foreach (var source in sourceList)
            {
                GenreVM target = new GenreVM
                {
                    GenreID = source.GenreID,
                    Name = source.Name,
                    Description = source.Description
                };
                targetList.Add(target);
            }
            return View(targetList);
        }


        public ActionResult Details(int id)
        {
            return View();
        }


        public ActionResult Create()
        {
            return View(new GenreVM());
        }


        [HttpPost]
        public ActionResult Create(GenreVM viewModel)
        {
            try
            {
                genreService.Add(new Genre { Name = viewModel.Name, Description = viewModel.Description });
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Genre/Edit/5
        public ActionResult Edit(int id)
        {
            var entity = genreService.FindBy(x => x.GenreID == id);
            GenreVM viewModel = new GenreVM
            {
                GenreID = entity.GenreID,
                Name = entity.Name,
                Description = entity.Description
            };
            return View(viewModel);
        }

        // POST: Genre/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, GenreVM source)
        {
            try
            {
                Genre target = new Genre
                {
                    GenreID = source.GenreID,
                    Name = source.Name,
                    Description = source.Description
                };
                genreService.Edit(target);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Genre/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Genre/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Web/GyandhaaraLibrary.View/Controllers/LanguageController.cs
using GyandhaaraLibrary.DataModel;
using GyandhaaraLibrary.Service;
using GyandhaaraLibrary.Service.Interfaces;
using GyandhaaraLibrary.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GyandhaaraLibrary.View.Controllers
{
    public class LanguageController : Controller
    {
        ILanguageService languageService;
        public LanguageController()
        {
            languageService = new LanguageService();
        }

        public ActionResult Index()
        {
            IList<LanguageVM> targetList = new List<LanguageVM>();
            IEnumerable<Language> sourceList = languageService.GetAll().ToList();
            foreach (var source in sourceList)
            {
                LanguageVM target = new LanguageVM
                {
                    LanguageID = source.LanguageID,
                    Name = source.Name,
                    Description = source.Description
                };
                targetList.Add(target);
            }
            return View(targetList);
        }

        public ActionResult Create()
        {
            return View(new LanguageVM());
        }

        [HttpPost]
        public ActionResult Create(LanguageVM source)
        {
            try
            {
                Language target = new Language
                {
                    LanguageID = source.LanguageID,
                    Name = source.Name,
                    Description = source.Description
                };
                languageService.Add(target);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            var source = languageService.FindBy(x => x.LanguageID == id);
            LanguageVM target = new LanguageVM
            {
                LanguageID = source.LanguageID,
                Name = source.Name,
                Description = source.Description
            };
            return View(target);
        }

        [HttpPost]
        public ActionResult Edit(int id, LanguageVM source)
        {
            try
            {
                Language target = new Language
                {
                    LanguageID = source.LanguageID,
                    Name = source.Name,
                    Description = source.Description
                };
                languageService.Edit(target);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Web/GyandhaaraLibrary.View/Controllers/SupplierController.cs
using GyandhaaraLibrary.DataModel;
using GyandhaaraLibrary.Service;
using GyandhaaraLibrary.Service.Interfaces;
using GyandhaaraLibrary.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GyandhaaraLibrary.View.Controllers
{
    public class SupplierController : Controller
    {
        ISupplierService supplierService;

        public SupplierController()
        {
            supplierService = new SupplierService();
        }

        public ActionResult Index()
        {
            IList<IndexSupplierVM> targetList = new List<IndexSupplierVM>();
            IEnumerable<Supplier> sourceList = supplierService.GetAll().ToList();
            foreach (var source in sourceList)
            {
                IndexSupplierVM target = new IndexSupplierVM
                {
                    SupplierID = source.SupplierID,
                    Name = source.Name,
                    Contact = source.Contact,
                    Email = source.Email
                };
                targetList.Add(target);
            }
            return View(targetList);
        }

        public ActionResult Details(int id)
        {
            var source = supplierService.GetSupplierByID(id);
            AddSupplierViewModel target = new AddSupplierViewModel
            {
                SupplierID = source.SupplierID,
                Name = source.Name,
                Contact = source.Contact,
                Email = source.Email,
                AddressID = source.AddressID.Value,
                Street = source.Address.Street,
                City = source.Address.City,
                State = source.Address.State,
                Country = source.Address.Country,
                ZipCode = source.Address.ZipCode
            };
            return View(target);
        }

        public ActionResult Create()
        {
            return View(new AddSupplierViewModel());
        }

        [HttpPost]
        public ActionResult Create(AddSupplierViewModel source)
        {
            try
            {
                Supplier target = new Supplier
                {
                    Name = source.Name,
                    Contact = source.Contact,
                    Email = source.Email,
                    Address = new Address
                    {
                        Street = source.Street,
                        City = source.City,
                        State = source.State,
                        Country = source.Country,
                        ZipCode = source.ZipCode
                    }
                };
                supplierService.Add(target);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            var source = supplierService.GetSupplierByID(id);
            AddSupplierViewModel target = new AddSupplierViewModel
            {
                SupplierID = source.SupplierID,
                Name = source.Name,
                Contact = source.Contact,
                Email = source.Email,
                AddressID = source.AddressID.Value,
                Street = source.Address.Street,
                City = source.Address.City,
                State = source.Address.State,
                Country = source.Address.Country,
                ZipCode = source.Address.ZipCode
            };
            return View(target);
        }

        [HttpPost]
        public ActionResult Edit(int id, AddSupplierViewModel source)
        {
            try
            {
                Supplier target = new Supplier
                {
                    SupplierID = source.SupplierID,
                    Name = source.Name,
                    Contact = source.Contact,
                    Email = source.Email,
                    Address = new Address
                    {
                        AddressID = source.AddressID,
                        Street = source.Street,
                        City = source.City,
                        State = source.State,
                        Country = source.Country,
                        ZipCode = source.ZipCode
                    }
                };
                supplierService.Edit(target);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Web/GyandhaaraLibrary.View/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - GyandhaaraLibrary</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index","Home")">GYAN DHAARA LIBRARY</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="@Url.Action("Index","Home")">HOME</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#"><span class="glyphicon glyphicon-user"></span>Sign Up</a></li>
                    <li><a href="#"><span class="glyphicon glyphicon-log-in"></span>Login</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container-fluid text-center">
        <div class="row content">
            <!-- side bar -->
            <div class="col-sm-2 sidenav">
                <div class="list-group">
                    <a href="#" class="list-group-item">DASHBOARD</a>
                    <a href="@Url.Action("Index","Book")" class="list-group-item">BOOKS</a>
                    <a href="@Url.Action("Index","Genre")" class="list-group-item">GENRE</a>
                    <a href="@Url.Action("Index","Language")" class="list-group-item">LANGUAGE</a>
                    <a href="@Url.Action("Index", "Supplier")" class="list-group-item">SUPPLIER</a>
                </div>
            </div>
            <!-- side bar -->
            <!-- main content-->
            <div class="col-sm-10 text-left" style="padding-top: 20px;">
                @RenderBody()
            </div>
            <!-- main content-->
        </div>
    </div>

    <footer>
        <div class="navbar navbar-inverse navbar-fixed-bottom">
            <div class="container">
                <div class="navbar-collapse collapse" id="footer-body">
                    <ul class="nav navbar-nav">
                        <li><a href="#">GYAN DHAARA LIBRARY</a></li>
                        <li><a href="#">DASHBOARD</a></li>
                        <li><a href="#">BOOKS</a></li>
                        <li><a href="#">GENRE</a></li>
                        <li><a href="#">SUPPLIER</a></li>
                        <li><a href="#">&copy; GYANDHAARA.COM</a></li>
                    </ul>
                </div>
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#footer-body">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryUI")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
        $(function () {
            $('#publishedDatePicker').datepicker({
                dateFormat: 'yy-mm-dd'
            }).datepicker("setDate", new Date());
        });
        $(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
        $(function () {
            $('#entryDatePicker').datepicker({
                dateFormat: 'yy-mm-dd'
            }).datepicker("setDate", new Date());
        });

        $(document).on('click', '#add-Genre', function () {
            $('#addGenreModal').modal('show');
        });

        $('#genreChecked').click(function () {
            $('#genreChecked').not(this).prop('checked', false);
        })
    </script>
</body>
</html>